import { Account } from "src/app/shares/model/account";

export const accountDatas: Account[] = [
  {
    id: 1,
    accountId: '001002003',
    accountName: 'Ean Dalin',
    accountBalace: 90.00,
    currency: 'USD',
    accountType: 'adm',
    status: 'Active',
  },
  {
    id: 2,
    accountId: '000000002',
    accountName: 'Sopheary Chhay',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'adm',
    status: 'Active',
  },
  {
    id: 3,
    accountId: '000000003',
    accountName: 'Phu Sok oudom',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'adm',
    status: 'Active',
  },
// admi

  {
    id: 7,
    accountId: '000000007',
    accountName: 'Chiev Raksmey',
    accountBalace: 90.00,
    currency: 'USD',
    accountType: 'seni',
    status: 'Active',
  },
  {
    id: 8,
    accountId: '000000008',
    accountName: 'Sophat Rourn',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'seni',
    status: 'Active',
  },
  {
    id: 9,
    accountId: '000000009',
    accountName: 'Khuon Paly',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'seni',
    status: 'Active',
  },
  // seni
  {
    id: 4,
    accountId: '000000004',
    accountName: 'Vi Rak',
    accountBalace: 90.00,
    currency: 'USD',
    accountType: 'mast',
    status: 'Active',
  },
  {
    id: 5,
    accountId: '000000005',
    accountName: 'Vanna Keovoreak',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'mast',
    status: 'Active',
  },
  {
    id: 6,
    accountId: '000000006',
    accountName: 'Hoem Neth',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'mast',
    status: 'Active',
  },
// agent
  {
    id: 10,
    accountId: '000000010',
    accountName: 'Lue Kongsun',
    accountBalace: 90.00,
    currency: 'USD',
    accountType: 'agen',
    status: 'Active',
  },
  {
    id: 11,
    accountId: '000000011',
    accountName: 'Tha Nit TK',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'agen',
    status: 'Active',
  },
  {
    id: 12,
    accountId: '000000012',
    accountName: 'Puthary Chiev',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'agen',
    status: 'Active',
  },
  {
    id: 13,
    accountId: '000000013',
    accountName: 'Chhor Deth',
    accountBalace: 90.00,
    currency: 'USD',
    accountType: 'memb',
    status: 'Active',
  },
  {
    id: 14,
    accountId: '000000014',
    accountName: 'Srey Man',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'memb',
    status: 'Active',
  },
  {
    id: 15,
    accountId: '000000015',
    accountName: 'Srey Pich',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'memb',
    status: 'Active',
  },
  {
    id: 16,
    accountId: '000000016',
    accountName: 'Srey Pich',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'memb',
    status: 'Active',
  },
  {
    id: 17,
    accountId: '000000016',
    accountName: 'Srey Pich',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'memb',
    status: 'Active',
  },
  {
    id: 18,
    accountId: '000000016',
    accountName: 'Srey Pich',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'memb',
    status: 'Active',
  },
  {
    id: 19,
    accountId: '000000016',
    accountName: 'Srey Pich',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'memb',
    status: 'Active',
  },
  {
    id: 20,
    accountId: '000000016',
    accountName: 'Srey Pich',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'memb',
    status: 'Active',
  },
  {
    id: 21,
    accountId: '000000016',
    accountName: 'Srey Pich',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'memb',
    status: 'Active',
  },
  {
    id: 22,
    accountId: '000000016',
    accountName: 'Srey Pich',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'memb',
    status: 'Active',
  },
  {
    id: 23,
    accountId: '000000016',
    accountName: 'Srey Pich',
    accountBalace: 190.00,
    currency: 'USD',
    accountType: 'memb',
    status: 'Active',
  }
];
